type: object
name: FooterConfig
label: Footer Config
fields:
  - type: string
    name: title
    label: Title
  - type: list
    name: contactLinks
    label: Contact links
    items:
      - type: model
        models:
          - Link
  - type: list
    name: socialLinks
    label: Social links
    items:
      - type: model
        models:
          - Link
